export const attributes = [
  {
    _id: "attributecolorjp8ddu14m7vf40l6d697db82",
    name: "Color",
    slug: "color",
    options: [
      {
        _id: "color8641205793qwertasdfg",
        slug: "color-gray",
        label: "Gray",
        display: "Gray",
        hex: "#6b7280",
        textColor: "#ffffff",
      },
      {
        _id: "colorlblsl59042va1ff9269t0v",
        slug: "color-graphite-gray",
        label: "Graphite Gray",
        display: "Graphite Gray",
        hex: "#4B4E53",
        textColor: "#ffffff",
      },
      {
        _id: "colordg0003k8ssdewg3m000435",
        slug: "color-deep-navy",
        label: "Deep Navy",
        display: "Deep Navy",
        hex: "#000435",
        textColor: "#ffffff",
      },
      {
        _id: "colordg0003k8s3m49k5i8",
        slug: "color-gunmetal-gray",
        label: "Gunmetal Gray",
        display: "Gunmetal Gray",
        hex: "#353E43",
        textColor: "#ffffff",
      },
      {
        _id: "colory38wx95zy38cjzw85127sr",
        slug: "color-dark-red",
        label: "Dark Red",
        display: "Dark Red",
        hex: "#8B0000",
        textColor: "#ffffff",
      },
      {
        _id: "color8gc7t83h8ifre332fdwx1884",
        slug: "color-midnight-navy",
        label: "Midnight Navy",
        display: "Midnight Navy",
        hex: "#364251",
        textColor: "#ffffff",
      },
      {
        _id: "colorw6n58ij4i91429qdxafj25v5",
        slug: "color-neon-yellow",
        label: "Neon Yellow",
        display: "Neon Yellow",
        hex: "#EFFF00",
        textColor: "#474747",
      },
      {
        _id: "color1s9acdljp780sik8k805544y",
        slug: "color-brown",
        label: "Brown",
        display: "Brown",
        hex: "#7C5A3C",
        textColor: "#ffffff",
      },
      {
        _id: "color5712064893plmkonjibv",
        slug: "color-green",
        label: "Green",
        display: "Green",
        hex: "#10b981",
        textColor: "#ffffff",
      },
      {
        _id: "color4728169530qazwsxedcr",
        slug: "color-red",
        label: "Red",
        display: "Red",
        hex: "#ef4444",
        textColor: "#ffffff",
      },
      {
        _id: "color6139475208bnmasdfghj",
        slug: "color-black",
        label: "Black",
        display: "Black",
        hex: "#000000",
        textColor: "#ffffff",
      },
      {
        _id: "color3057921648rfvtgbynum",
        slug: "color-white",
        label: "White",
        display: "White",
        hex: "#ffffff",
        textColor: "#393939",
      },
      {
        _id: "colornf5l06769c5ih648xmr7zb8b",
        slug: "color-orange",
        label: "Orange",
        display: "Orange",
        hex: "#F97316",
        textColor: "#ffffff",
      },
      {
        _id: "color670doyqs79397wt9qzx12o",
        slug: "color-navy-blue",
        label: "Navy Blue",
        display: "Navy Blue",
        hex: "#1F2A44",
        textColor: "#ffffff",
      },
      {
        _id: "colorap7fqda207030f61c15wli",
        slug: "color-navy",
        label: "Navy",
        display: "Navy",
        hex: "#000080",
        textColor: "#ffffff",
      },
      {
        _id: "colora3m96gu6o3jjj75l4n3v11",
        slug: "color-geode-teal",
        label: "Geode Teal",
        display: "Geode Teal",
        hex: "#005147",
        textColor: "#ffffff",
      },
      {
        _id: "color053hv80oq8x7gme849k9dc",
        slug: "color-dark-navy-blue",
        label: "Dark Navy Blue",
        display: "Dark Navy Blue",
        hex: "#0A1F44",
        textColor: "#ffffff",
      },
      {
        _id: "color7fsb642eu91kw53a172dos0n",
        slug: "color-maroon",
        label: "Maroon",
        display: "Maroon",
        hex: "#800000",
        textColor: "#ffffff",
      },
      {
        _id: "colorlx8bj3f8490i2io0m6d2ed68",
        slug: "color-blue",
        label: "Blue",
        display: "Blue",
        hex: "#0000FF",
        textColor: "#ffffff",
      },
      {
        _id: "colorh4i8zmm5iei14j2638pm96",
        slug: "color-olive-haze",
        label: "Olive Haze",
        display: "Olive Haze",
        hex: "#888165",
        textColor: "#ffffff",
      },
    ],
  },
{
    _id: "attributeshoesizeus3948201756lkjhgfdsaq",
    name: "Shoe Size",
    slug: "shoe-size",
    options: [
      {
        _id: "shoesize4yy853ynjily356o39",
        slug: "shoe-size-5",
        label: "5",
        display: "5",
      },
      {
        _id: "shoesizedfbjdn584xz12471r8",
        slug: "shoe-size-5.5",
        label: "5.5",
        display: "5.5",
      },
      {
        _id: "shoesize6d9l3oc58969gtzq1d",
        slug: "shoe-size-6",
        label: "6",
        display: "6",
      },
      {
        _id: "shoesizead407s0adu66c08i7u",
        slug: "shoe-size-6.5",
        label: "6.5",
        display: "6.5",
      },
      {
        _id: "shoesize7802643915mnbvcxzpoi",
        slug: "shoe-size-7",
        label: "7",
        display: "7",
      },
      {
        _id: "shoesize1594730286asdfqwerty",
        slug: "shoe-size-7.5",
        label: "7.5",
        display: "7.5",
      },
      {
        _id: "shoesize6081529473plokijuhyg",
        slug: "shoe-size-8",
        label: "8",
        display: "8",
      },
      {
        _id: "shoesize5729486310zxcvbnmwer",
        slug: "shoe-size-8.5",
        label: "8.5",
        display: "8.5",
      },
      {
        _id: "shoesize9415723086qazwsxedcr",
        slug: "shoe-size-9",
        label: "9",
        display: "9",
      },
      {
        _id: "shoesize8372059146rfvtgbynuh",
        slug: "shoe-size-9.5",
        label: "9.5",
        display: "9.5",
      },
      {
        _id: "shoesize2169370548okmijnuhbv",
        slug: "shoe-size-10",
        label: "10",
        display: "10",
      },
      {
        _id: "shoesize6958032147plokmijnuy",
        slug: "shoe-size-10.5",
        label: "10.5",
        display: "10.5",
      },
      {
        _id: "shoesize4739205618xswedcvfrt",
        slug: "shoe-size-11",
        label: "11",
        display: "11",
      },
      {
        _id: "shoesize8206593147tyghbnujmi",
        slug: "shoe-size-11.5",
        label: "11.5",
        display: "11.5",
      },
      {
        _id: "shoesize1574926038qwertasdfg",
        slug: "shoe-size-12",
        label: "12",
        display: "12",
      },
      {
        _id: "shoesize9384710526zxcvbnmasd",
        slug: "shoe-size-13",
        label: "13",
        display: "13",
      },
    ],
    createdBy: "user43210987nopqrstu",
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-15T11:00:00Z",
  },
]